
configuration.click(configuration.find(".audio_play_button"),function(){var f=this.getAttribute("data-src-mp3");var h=this.getAttribute("data-lang");var d=this.parentNode.classList.contains("exa_sound")?"Sound TTS":"Sound";
var c=false;try{var b=document.createElement("audio");c=b.canPlayType&&b.canPlayType("audio/mpeg")!="no"&&b.canPlayType("audio/mpeg")!=""}catch(g){}if(!c){window.open(f,"Sound","menubar=no, status=no, scrollbars=no, menubar=no, width=200, height=100");
sendGaEvent(d,h,"Popup");return}if(window.audio!=null&&!window.audio.ended){window.audio.pause();window.audio.currentTime=0}window.audio=new Audio(f);audio.addEventListener("error",function(a){alert("Apologies, the sound is not available."+JSON.stringify(a));
sendGaEvent(d,h,"Error")});audio.play();sendGaEvent(d,h,"HTML5")});(function(){var a=function(){if(typeof(NoScrollOnClick)==="function"){g=new NoScrollOnClick(c,false,true)}else{setTimeout(function(){a()},500)}};var f=configuration.findUnique("#share-modal");if(f){var c=configuration.find(".share-button");
var g;a();var e=function(){f.className+=" share-overlay-on"};var d=function(){if(f.className.indexOf("share-overlay-on")>-1){f.className=f.className.replace("share-overlay-on","");b()}};var b=function(){if(g.isSlide){g.onClick()
}};document.addEventListener("keyup",function(h){if(h.keyCode==27){d()}});f.children[0].addEventListener("click",function(h){h.stopPropagation()},false);f.addEventListener("click",d);configuration.findUnique(".share-close",f).addEventListener("click",d);
configuration.click(c,e)}})();(function(){var a=function(){if(typeof(NoScrollOnClick)==="function"){g=new NoScrollOnClick(c,false,true)}else{setTimeout(function(){a()},500)}};var f=configuration.findUnique("#popup-frequency");
if(f){var c=configuration.find(".word-frequency-icon");var g;a();var e=function(){f.className+=" share-overlay-on"};var d=function(){if(f.className.indexOf("share-overlay-on")>-1){f.className=f.className.replace("share-overlay-on","");
b()}};var b=function(){if(g.isSlide){g.onClick()}};document.addEventListener("keyup",function(h){if(h.keyCode==27){d()}});f.children[0].addEventListener("click",function(h){h.stopPropagation()},false);
f.addEventListener("click",d);configuration.findUnique(".popup-close-frequency",f).addEventListener("click",d);configuration.click(c,e)}})();(function(){var a=function(){if(typeof(NoScrollOnClick)==="function"){g=new NoScrollOnClick(c,false,true)
}else{setTimeout(function(){a()},500)}};var f=configuration.findUnique("#popup-modal");if(f){var c=configuration.find(".popup-button");configuration.click(configuration.find(".popup-button .url"),function(h){h.preventDefault();
return false});var g;a();var e=function(){f.className+=" popup-overlay-on"};var d=function(){if(f.className.indexOf("popup-overlay-on")>-1){f.className=f.className.replace("popup-overlay-on","");b()}};
var b=function(){if(g.isSlide){g.onClick()}};document.addEventListener("keyup",function(h){if(h.keyCode==27){d()}});f.children[0].addEventListener("click",function(h){h.stopPropagation()},false);f.addEventListener("click",d);
configuration.findUnique(".popup-close",f).addEventListener("click",d);configuration.click(c,function(){e();var h=document.getElementById("credit-info");if(h.firstChild){h.removeChild(h.firstChild)}h.appendChild(this.cloneNode(true))
})}})();(function(){var a=function(){if(typeof(NoScrollOnClick)==="function"){g=new NoScrollOnClick(c,false,true)}else{setTimeout(function(){a()},500)}};var f=configuration.findUnique("#pron-sound-modal");
if(f){var c=configuration.find(".pron-sound-button");var g;a();var e=function(){f.className+=" pron-sound-overlay-on"};var d=function(){if(f.className.indexOf("pron-sound-overlay-on")>-1){f.className=f.className.replace("pron-sound-overlay-on","");
configuration.findUnique("audio",f).pause();b()}};var b=function(){if(g.isSlide){g.onClick()}};document.addEventListener("keyup",function(h){if(h.keyCode==27){d()}});f.children[0].addEventListener("click",function(h){h.stopPropagation()
},false);f.addEventListener("click",d);configuration.findUnique(".pron-sound-close",f).addEventListener("click",d);configuration.click(c,e)}})();var navigationDisplayer;var animateScrolling;var displayButtNav;var navigationNavCick;var selectAuto;var scrollToActivate=false;var windowElm=window;(function(){var n;var j=configuration.findUnique(".navigation");
var c=(typeof entryPage!=="undefined")?entryPage:0;if(!j){n=configuration.cewa("div",{"class":"tabsNavigation"});j=configuration.cewa("div",{"class":"navigation"});j.appendChild(n)}else{n=configuration.findUnique(".tabsNavigation",j)
}if(!n){return}function k(q,a){var p="";if(q.getAttribute(a)){p=q.getAttribute(a)}return p}function e(q,p,t){var r=q.replace(":","").trim();if(p&&p!=""){r+=": "+p}if(t&&t!=""){r+="<span class='expo'>"+t+"</span>"
}return r}var g=document.createDocumentFragment();configuration.find("*[data-type-block]").forEach(function(A,t){if(c>1){return}var p=Math.random();var r=A;r.setAttribute("data-id",p);var q=k(r,"data-type-block");
if(q===""){return}var u=k(r,"data-title-block");var z=k(r,"data-num-block");if(configuration.find(".navigation *[data-id='"+p+"'][data-type-block-tab='"+q.replace(/'/g,"\\'")+"'][data-title-block-tab='"+u.replace(/'/g,"\\'")+"'][data-num-block-tab='"+z.replace(/'/g,"\\'")+"']",n).length===0){var B=configuration.cewa("a",{"class":"tab"});
B.setAttribute("data-type-block-tab",q);B.setAttribute("data-title-block-tab",u);B.setAttribute("data-num-block-tab",z);B.setAttribute("data-id",p);B.innerHTML=(k(r,"data-type-block-nochange")=="true")?q:e(q,u,z);
if(!(new RegExp("(grammar|english-thesaurus)")).test(pageDictCode)&&!r.classList.contains("cB-img")&&!r.classList.contains("cB-v")){var x=configuration.getParent(r,".he"),w=configuration.getParent(r,".dictentry");
if(w){r=w}else{if(x&&configuration.getParents(r,".assets").length===0){r=x}}}var y=configuration.cewa("span");y.appendChild(B);g.appendChild(y);B.addEventListener("click",function(){var a=this;var C=this.getAttribute("data-type-block-tab");
if(C&&headword){sendGaEvent("NavigationTabInnerPage",pageDictCode,C)}if(!configuration.findUnique("#navigation-menu").classList.contains("collapsed")){var D=configuration.findUnique("#navigation-menu");
if(!D.classList.contains("collapsed")){D.classList.add("collapsed");var s=configuration.find(".tab.current");for(var v=0;v<s.length;v++){s[v].classList.add("collapsedStatus")}}}animateScrolling(a,r)})}});
window.addEventListener("load",function(){var q=configuration.findUnique("#navigation-menu");if(q.children.length>1){var a=configuration.find(".tab.current");for(var p=0;p<a.length;p++){a[p].classList.remove("noDisplayArrow")
}}if(typeof tocLabel!=="undefined"&&tocLabel){i()}else{q.appendChild(this);if(q.children.length>1){var a=configuration.find(".tab.current");for(var p=0;p<a.length;p++){a[p].classList.remove("noDisplayArrow")
}}}configuration.click(configuration.find(".navigation > .tabsNavigation> a.tab"),function(){var r=this;var s=this.getAttribute("title");if(s){sendGaEvent("NavigationTabSubMenu",pageDictCode,s)}})}.bind(g));
function i(){configuration.click(configuration.find("#navigation-menu a.tab"),function(){var a=this;if(!configuration.findUnique("#navigation-menu").classList.contains("collapsed")){var s=configuration.findUnique("#navigation-menu");
if(!s.classList.contains("collapsed")){s.classList.add("collapsed");var p=configuration.find(".tab.current");for(var q=0;q<p.length;q++){p[q].classList.add("collapsedStatus")}}}var t=configuration.findUnique("[data-id-idm-toc='"+this.getAttribute("data-id")+"']");
animateScrolling(a,t);var r=this.getAttribute("data-type-block-tab");if(r&&headword){sendGaEvent("NavigationTabMenu",pageDictCode,r+"-"+headword)}})}configuration.click(configuration.find(".tab a"),function(){if(configuration.find(".thesbase").length==0){return
}var a=this;animateScrolling(a.parentNode,a.getAttribute("href"));return false});animateScrolling=function(p,s){scrollToActivate=true;p.classList.add("current");var r=document.querySelectorAll("header,.padding-pub>.menuDd,.navigation[data-position=fixed]");
var a=0;for(var q=0;q<r.length;q++){a+=r[q].getBoundingClientRect().height}configuration.animate(configuration.find("body,html"),{scrollTop:window.scrollY+s.getBoundingClientRect().top-a},{duration:300,complete:function(){scrollToActivate=false
}})};var l=configuration.cewa("a",{"class":"tab nav left icon-caret-left","data-type-tab-nav":"left"});var m=configuration.cewa("a",{"class":"tab nav right icon-caret-right","data-type-tab-nav":"right"});
var g=document.createDocumentFragment();g.appendChild(l);g.appendChild(m);j.appendChild(g);var h=configuration.findUnique(".res_cell_center_content");if(h){h.insertBefore(j,h.firstChild)}navigationDisplayer=function(){if(configuration.getCookie("seleniumtest")!=null){return
}if(windowElm==undefined){return}var t=configuration.findUnique(".tabsNavigation");if(j.children.length<=2||(t!=null&&t.children.length==0)){configuration.hide(j);return}var p=configuration.findUnique(".navigation:not([data-position])");
var q=configuration.find(".navigation[data-position='fixed']");var u=q.length;var G=configuration.findUnique(".sticky");var r=document.querySelectorAll(".padding-pub>.menuDd");var A=0;if(r!=null){for(var y=0,B=r.length;
y<B;y++){A+=r[y].getBoundingClientRect().height}}var v=G!=null?G.offsetHeight:0;v+=A;var z=document.body.classList.contains("headerMinimized")?0:v;var F=configuration.getWidth(p);if(u>0){configuration.setCss(q[0],{top:z+"px",width:F+"px"})
}var E=(p!=null)?(windowElm.pageYOffset+z)-p.offsetTop:(windowElm.pageYOffset+z);if(E>=0){if(u>0){return}else{if(p!=null){var C=p.cloneNode(true);C.setAttribute("data-position","fixed");configuration.setCss(C,{top:z+"px",width:F+"px"});
configuration.click(configuration.find(".tab[data-title-block-tab]",C),function(){var s=this.getAttribute("data-id");var a=configuration.findUnique("*[data-type-block][data-id='"+s+"']");animateScrolling(this,a)
});configuration.click(configuration.find(".nav",C),navigationNavCick);configuration.click(configuration.find(".current",C),clickOnCurrent);h.appendChild(C);var D=configuration.findUnique(".tabsNavigation",p).scrollLeft;
configuration.findUnique(".tabsNavigation",C).scrollLeft=D}}}else{if(u>0){configuration.findUnique(".tabsNavigation",p).pageXOffset=configuration.findUnique(".tabsNavigation",q[0]).pageXOffset;configuration.remove(q[0])
}}};displayButtNav=function(){var s=configuration.find(".navigation .nav");var r=configuration.find(".navigation .right");var t=configuration.find(".navigation .left");var q=configuration.find(".navigation:first-child .tab");
var p=0;q.forEach(function(v){p+=v.offsetWidth});if(p<=configuration.getWidth(configuration.findUnique(".navigation"))){configuration.hide(s);return}if(!isNormalScreen){configuration.hide(s);configuration.findUnique(".tabsNavigation").style.overflowX="auto";
return}var a=n.scrollWidth-configuration.getWidth(j);var u=n.scrollLeft;if(u===0){configuration.show(r);configuration.hide(t)}else{if(u>=a){configuration.show(t);configuration.hide(r)}else{configuration.show(s)
}}};var f=false;navigationNavCick=function(){if(f){return}var y=this;var q=configuration.find(".tabsNavigation");var a=configuration.find(".tabsNavigation .tab");var w=q[0].pageXOffset;var z=configuration.getWidth(q[0]);
var A=q[0]["scrollWidth"];var u=A;if(y.classList.contains("left")){var s;for(var r=a.length-1;r>=0;r--){s=a[r];var p=s.offsetWidth;var t=s.offsetLeft-configuration.getWidth(y);if(w<t){continue}u=t;if(w-z<t){u=w;
continue}if(w-z>t){break}}var v=s.parentNode.children[0];if(v.length>0&&v[0]==s[0]){u=0}}else{for(var r=0,x=a.length;r<x;r++){var s=a[r];var p=s.offsetWidth;var t=s.offsetLeft-configuration.getWidth(y);
if(w>t){continue}u=t;if(w+z>t+p){u=w+z;continue}if(w+z<t+p){break}}}f=true;if(u>A){u=A}if(u<0){u=0}configuration.animate(q,{scrollLeft:u},{duration:300,complete:function(){f=false;displayButtNav()}})};
configuration.click(configuration.find(".navigation .nav"),navigationNavCick);function b(p){if(!p.getAttribute("data-tab")&&!p.getAttribute("data-id")){return -1}var a=(p.getAttribute("data-tab"))?p.getAttribute("data-tab").getAttribute("data-block"):p;
return(a.offsetTop)-configuration.getHeight(configuration.findUnique(".sticky"))}function d(t){var p=windowElm.pageYOffset;var a=t[0];var s=b(a);for(var q=1;q<t.length&&s<p;q++){var u=t[q];var r=b(u);if(r<=p&&r>0){a=u;
s=r}}return a}var o=configuration.find("*[data-type-block]");selectAuto=function(){scrollToActivate=scrollToActivate||false;if(scrollToActivate||o.length===0){return}var C=configuration.find(".tabsNavigation");
var y=[];C.forEach(function(z){y.push(z.parentNode)});var v=d(o);var u=v.getAttribute("data-id");var a=[];if(u){var s=k(v,"data-type-block");var t=k(v,"data-title-block");var B=k(v,"data-num-block");var x=[];
y.forEach(function(z){x.push(configuration.findUnique(".current",z))});var E=x[0];var q=x[1];if((E&&E.getAttribute("data-id")==u)||(q&&q.getAttribute("data-id")==u)){return}y.forEach(function(z){configuration.arrayFrom(configuration.find("*[data-type-block-tab]",z)).forEach(function(F){F.classList.remove("current")
})});var D="*[data-type-block-tab='"+s.replace(/'/g,"\\'")+"'][data-title-block-tab='"+t.replace(/'/g,"\\'")+"'][data-num-block-tab='"+B.replace(/'/g,"\\'")+"']";var p=[];C.forEach(function(z){p.push(configuration.findUnique(D,z))
});if(p.length==0){return}D+="[data-id='"+u+"']";C.forEach(function(F){var z=configuration.findUnique(D,F);z.classList.add("current");a.push(z)})}else{var D="[href='#"+v.getAttribute("id")+"']";var x=[];
y.forEach(function(z){x.push(configuration.findUnique(".current",z))});if(configuration.findUnique("a",x[0]).getAttribute("href")=="#"+v.getAttribute("id")||configuration.findUnique("a",x[1]).getAttribute("href")=="#"+v.getAttribute("id")){return
}y.forEach(function(z){configuration.findUnique(".tab",z).classList.remove("current")});var p=[];C.forEach(function(z){p.push(configuration.findUnique(D,z))});if(p.length==0){return}C.forEach(function(z){a.push(configuration.getParent(configuration.findUnique(D,z),".tab"))
});a.forEach(function(z){z.classList.add("current")})}var w=configuration.find(".navigation .nav");var r=[];w.forEach(function(z){if(configuration.isVisible(z)){r.push(z)}});var A=(r.length==0)?0:r[0].offsetWidth;
C.forEach(function(z){z.scrollLeft=a[0].offsetLeft-A})};displayButtNav();navigationDisplayer();window.addEventListener("beforeunload",function(){alert(1)})})();var lbl=configuration.findUnique(".lightboxLink");configuration.click(lbl,function(){var f=this;var c=configuration.cewa("img",{"class":"lightboxImage"});c.setAttribute("alt",f.getAttribute("data-alt"));
c.setAttribute("src",f.getAttribute("data-image"));var e=configuration.cewa("div",{"class":"lightboxCopyright"},f.getAttribute("data-copyright"));var i=configuration.cewa("a",{"class":"lightboxClose icon-times"});
var d=configuration.cewa("div",{"class":"lightboxContainer"});d.appendChild(i);d.appendChild(c);d.appendChild(e);var a=configuration.cewa("div",{"class":"lightboxOverlay"});a.appendChild(d);a.addEventListener("click",function(){b()
});body.appendChild(a);g();windowElm.addEventListener("resize",g);documentElm.addEventListener("keyup",h);function b(){configuration.fadeOut(a,200,function(){configuration.remove(a)});windowElm.removeEventListener("resize",g);
documentElm.removeEventListener("keyup",h)}function g(){configuration.setCss(c,{"max-width":(window.screen.width-10)+"px","max-height":(window.screen.height-60)+"px"})}function h(j){if(j.keyCode==27){b()
}}});windowElm.addEventListener("hashchange",function(b){var a=null;try{a=decodeURI(location.hash)}catch(b){return}var c;if(a){c=configuration.find(a);if(c.length>0){documentElm.scrollTop=c[0].offsetTop-configuration.getHeight(configuration.findUnique("header.sticky"))
}}});configuration.triggerEvent(windowElm,"hashchange","HTMLEvents");