
configuration.find(".cB-e.dcCorpEx").forEach(function(g){var c=10;var b=g;var a=configuration.arrayFrom(configuration.find(".exBox",b));if(a.length>c){var f=configuration.cewa("a",{"class":"button"},"$vs.gm('definition.example.showMore')");
var h=configuration.cewa("div",{"class":"example_overflow",style:"display:none;"});a.slice(c).forEach(function(i){h.appendChild(i)});var d=document.createDocumentFragment();d.appendChild(h).appendChild(f);
b.appendChild(d);f.addEventListener("click",function(){this.style.display="none";configuration.fadeIn(h)})}});window.addEventListener("load",function(){var a={button:null,popup:null,current_example:null,isPopupDisplayed:function(){return this.popup!==null&&this.button!==null&&this.current_example!==null
},openPopup:function(g){this.button=g;this.button.classList.add("current");this.current_example={exampleId:this.button.getAttribute("data-example-id")};this.popup=configuration.findUnique("#exReport");
this.refreshPopupPosition();configuration.fadeIn(this.popup,200);if(configuration.findUnique("#reason-other",this.popup)){configuration.findUnique("#reason-other",this.popup).addEventListener("click",function(h){configuration.findUnique("#reason-option-other").setAttribute("checked",true);
h.stopPropagation()})}this.popup.addEventListener("click",function(h){h.stopPropagation()})},refreshPopupPosition:function(){if(this.button!=null&&this.popup!=null){var g=this.button.parentNode;var j=g.offsetTop;
var i=g.getBoundingClientRect().top;var h;if(i<window.innerHeight/2){this.popup.classList.add("under");h=Math.round((j)+configuration.getHeight(g))}else{this.popup.classList.remove("under");h=Math.round(j-configuration.getHeight(this.popup))
}configuration.setCss(this.popup,{top:h+"px",left:(g.getBoundingClientRect().left+g.getBoundingClientRect().width-260)+"px"})}},closePopup:function(){if(this.popup!=null){configuration.fadeOut(this.popup,200,f);
this.popup=null}if(this.button!=null){this.button.classList.remove("current");this.button=null}this.current_example=null}};configuration.click(configuration.find(".ex_report"),function(g){a.isPopupDisplayed()?a.closePopup():a.openPopup(this);
g.stopPropagation()});var c=document.getElementById("exBtnCancel");if(c!=null){c.addEventListener("click",function(g){a.closePopup();g.stopPropagation()})}var e=document.getElementById("exBtnSummit");if(e!=null){e.addEventListener("click",function(l){var k=a.popup;
var j=b();if(j&&j.trim()!==""){var g=a.button.getAttribute("data-href");var i=g+"&reason="+encodeURIComponent(j);var h=new XMLHttpRequest();h.open("GET",i,true);h.onload=function(){if(this.status>=200&&this.status<400){d(k,"info","Thanks for contacting us! Your feedback will be reviewed within the next 5 working days.");
setTimeout(function(){a.closePopup()},4000)}else{d(k,"error","Your message send failed. Please, try again")}};h.onerror=function(){};h.send()}else{d(k,"error","Your messsage is empty.")}l.stopPropagation()
})}configuration.change(configuration.find(".reason-option"),function(h){var g=this.getAttribute("id")=="reason-option-other"?"focus":"blur";if(document.getElementById("reason-other")){document.getElementById("reason-other").dispatchEvent(new Event(g))
}h.stopPropagation()});document.body.addEventListener("click",function(g){if(a.isPopupDisplayed()){a.closePopup()}g.stopPropagation()});window.addEventListener("resize",a.refreshPopupPosition);window.addEventListener("scroll",a.refreshPopupPosition,{passive:true});
function b(){var h=configuration.findUnique(".reason-option:checked");if(!h){return null}var g=h.value;if(g=="on"){g=document.getElementById("reason-other").value}return g}function f(){var g=configuration.findUnique(".reason-option:checked");
if(g){g.checked=false}if(configuration.findUnique("#reason-other")){configuration.findUnique("#reason-other").value=""}configuration.setCss(configuration.findUnique("#exReport"),{top:"unset"})}function d(h,i,l){var k=configuration.arrayFrom(configuration.find(".message",h));
var j;var g=function(){j=configuration.cewa("div",{"class":"message "+i,style:"display:none;"});h.appendChild(j);j.innerHTML=l;configuration.slideDown(j,200)};if(k.length>0){k.forEach(function(m){configuration.slideUp(m,200,function(){configuration.remove(m);
g()})})}else{g()}setTimeout(function(){k.forEach(function(m){configuration.slideUp(m,200,function(){if(m!=null){configuration.remove(m)}})});configuration.remove(j)},4000)}});